// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tcpmsg.proto

/*
	Package tcpmsg_pb is a generated protocol buffer package.

	It is generated from these files:
		tcpmsg.proto

	It has these top-level messages:
		TcpmsgPackage
		TcpmsgHandshake
*/
package tcpmsg_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProtocolId int32

const (
	ProtocolId_PROTO_HANDSHAKE ProtocolId = 0
	ProtocolId_PROTO_EXTERNAL  ProtocolId = 255
)

var ProtocolId_name = map[int32]string{
	0:   "PROTO_HANDSHAKE",
	255: "PROTO_EXTERNAL",
}
var ProtocolId_value = map[string]int32{
	"PROTO_HANDSHAKE": 0,
	"PROTO_EXTERNAL":  255,
}

func (x ProtocolId) Enum() *ProtocolId {
	p := new(ProtocolId)
	*p = x
	return p
}
func (x ProtocolId) String() string {
	return proto.EnumName(ProtocolId_name, int32(x))
}
func (x *ProtocolId) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProtocolId_value, data, "ProtocolId")
	if err != nil {
		return err
	}
	*x = ProtocolId(value)
	return nil
}
func (ProtocolId) EnumDescriptor() ([]byte, []int) { return fileDescriptorTcpmsg, []int{0} }

type TcpmsgPackage struct {
	Pid              *ProtocolId `protobuf:"varint,1,req,name=Pid,enum=tcpmsg.pb.ProtocolId" json:"Pid,omitempty"`
	PlLen            *uint32     `protobuf:"varint,2,req,name=PlLen" json:"PlLen,omitempty"`
	Payload          []byte      `protobuf:"bytes,3,opt,name=Payload" json:"Payload,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *TcpmsgPackage) Reset()                    { *m = TcpmsgPackage{} }
func (m *TcpmsgPackage) String() string            { return proto.CompactTextString(m) }
func (*TcpmsgPackage) ProtoMessage()               {}
func (*TcpmsgPackage) Descriptor() ([]byte, []int) { return fileDescriptorTcpmsg, []int{0} }

func (m *TcpmsgPackage) GetPid() ProtocolId {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ProtocolId_PROTO_HANDSHAKE
}

func (m *TcpmsgPackage) GetPlLen() uint32 {
	if m != nil && m.PlLen != nil {
		return *m.PlLen
	}
	return 0
}

func (m *TcpmsgPackage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type TcpmsgHandshake struct {
	NodeId           []byte                      `protobuf:"bytes,1,req,name=NodeId" json:"NodeId,omitempty"`
	ProtoNum         *uint32                     `protobuf:"varint,2,req,name=ProtoNum" json:"ProtoNum,omitempty"`
	Protocols        []*TcpmsgHandshake_Protocol `protobuf:"bytes,3,rep,name=Protocols" json:"Protocols,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *TcpmsgHandshake) Reset()                    { *m = TcpmsgHandshake{} }
func (m *TcpmsgHandshake) String() string            { return proto.CompactTextString(m) }
func (*TcpmsgHandshake) ProtoMessage()               {}
func (*TcpmsgHandshake) Descriptor() ([]byte, []int) { return fileDescriptorTcpmsg, []int{1} }

func (m *TcpmsgHandshake) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *TcpmsgHandshake) GetProtoNum() uint32 {
	if m != nil && m.ProtoNum != nil {
		return *m.ProtoNum
	}
	return 0
}

func (m *TcpmsgHandshake) GetProtocols() []*TcpmsgHandshake_Protocol {
	if m != nil {
		return m.Protocols
	}
	return nil
}

type TcpmsgHandshake_Protocol struct {
	Pid              *ProtocolId `protobuf:"varint,1,req,name=Pid,enum=tcpmsg.pb.ProtocolId" json:"Pid,omitempty"`
	Ver              []byte      `protobuf:"bytes,2,req,name=Ver" json:"Ver,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *TcpmsgHandshake_Protocol) Reset()         { *m = TcpmsgHandshake_Protocol{} }
func (m *TcpmsgHandshake_Protocol) String() string { return proto.CompactTextString(m) }
func (*TcpmsgHandshake_Protocol) ProtoMessage()    {}
func (*TcpmsgHandshake_Protocol) Descriptor() ([]byte, []int) {
	return fileDescriptorTcpmsg, []int{1, 0}
}

func (m *TcpmsgHandshake_Protocol) GetPid() ProtocolId {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ProtocolId_PROTO_HANDSHAKE
}

func (m *TcpmsgHandshake_Protocol) GetVer() []byte {
	if m != nil {
		return m.Ver
	}
	return nil
}

func init() {
	proto.RegisterType((*TcpmsgPackage)(nil), "tcpmsg.pb.TcpmsgPackage")
	proto.RegisterType((*TcpmsgHandshake)(nil), "tcpmsg.pb.TcpmsgHandshake")
	proto.RegisterType((*TcpmsgHandshake_Protocol)(nil), "tcpmsg.pb.TcpmsgHandshake.Protocol")
	proto.RegisterEnum("tcpmsg.pb.ProtocolId", ProtocolId_name, ProtocolId_value)
}
func (m *TcpmsgPackage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TcpmsgPackage) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Pid == nil {
		return 0, new(proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x8
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(*m.Pid))
	}
	if m.PlLen == nil {
		return 0, new(proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x10
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(*m.PlLen))
	}
	if m.Payload != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(len(m.Payload)))
		i += copy(dAtA[i:], m.Payload)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *TcpmsgHandshake) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TcpmsgHandshake) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.NodeId == nil {
		return 0, new(proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(len(m.NodeId)))
		i += copy(dAtA[i:], m.NodeId)
	}
	if m.ProtoNum == nil {
		return 0, new(proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x10
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(*m.ProtoNum))
	}
	if len(m.Protocols) > 0 {
		for _, msg := range m.Protocols {
			dAtA[i] = 0x1a
			i++
			i = encodeVarintTcpmsg(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *TcpmsgHandshake_Protocol) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TcpmsgHandshake_Protocol) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Pid == nil {
		return 0, new(proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x8
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(*m.Pid))
	}
	if m.Ver == nil {
		return 0, new(proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTcpmsg(dAtA, i, uint64(len(m.Ver)))
		i += copy(dAtA[i:], m.Ver)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintTcpmsg(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *TcpmsgPackage) Size() (n int) {
	var l int
	_ = l
	if m.Pid != nil {
		n += 1 + sovTcpmsg(uint64(*m.Pid))
	}
	if m.PlLen != nil {
		n += 1 + sovTcpmsg(uint64(*m.PlLen))
	}
	if m.Payload != nil {
		l = len(m.Payload)
		n += 1 + l + sovTcpmsg(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *TcpmsgHandshake) Size() (n int) {
	var l int
	_ = l
	if m.NodeId != nil {
		l = len(m.NodeId)
		n += 1 + l + sovTcpmsg(uint64(l))
	}
	if m.ProtoNum != nil {
		n += 1 + sovTcpmsg(uint64(*m.ProtoNum))
	}
	if len(m.Protocols) > 0 {
		for _, e := range m.Protocols {
			l = e.Size()
			n += 1 + l + sovTcpmsg(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *TcpmsgHandshake_Protocol) Size() (n int) {
	var l int
	_ = l
	if m.Pid != nil {
		n += 1 + sovTcpmsg(uint64(*m.Pid))
	}
	if m.Ver != nil {
		l = len(m.Ver)
		n += 1 + l + sovTcpmsg(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovTcpmsg(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozTcpmsg(x uint64) (n int) {
	return sovTcpmsg(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *TcpmsgPackage) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTcpmsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TcpmsgPackage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TcpmsgPackage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pid", wireType)
			}
			var v ProtocolId
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (ProtocolId(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Pid = &v
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlLen", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.PlLen = &v
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTcpmsg
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = append(m.Payload[:0], dAtA[iNdEx:postIndex]...)
			if m.Payload == nil {
				m.Payload = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTcpmsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTcpmsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return new(proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TcpmsgHandshake) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTcpmsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TcpmsgHandshake: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TcpmsgHandshake: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTcpmsg
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeId = append(m.NodeId[:0], dAtA[iNdEx:postIndex]...)
			if m.NodeId == nil {
				m.NodeId = []byte{}
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProtoNum", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ProtoNum = &v
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Protocols", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTcpmsg
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Protocols = append(m.Protocols, &TcpmsgHandshake_Protocol{})
			if err := m.Protocols[len(m.Protocols)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTcpmsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTcpmsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return new(proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TcpmsgHandshake_Protocol) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTcpmsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Protocol: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Protocol: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pid", wireType)
			}
			var v ProtocolId
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (ProtocolId(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Pid = &v
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ver", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTcpmsg
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ver = append(m.Ver[:0], dAtA[iNdEx:postIndex]...)
			if m.Ver == nil {
				m.Ver = []byte{}
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipTcpmsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTcpmsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return new(proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTcpmsg(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTcpmsg
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTcpmsg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthTcpmsg
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowTcpmsg
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipTcpmsg(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthTcpmsg = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTcpmsg   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("tcpmsg.proto", fileDescriptorTcpmsg) }

var fileDescriptorTcpmsg = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x49, 0x2e, 0xc8,
	0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0xf1, 0x92, 0x94, 0x32, 0xb8,
	0x78, 0x43, 0xc0, 0x9c, 0x80, 0xc4, 0xe4, 0xec, 0xc4, 0xf4, 0x54, 0x21, 0x75, 0x2e, 0xe6, 0x80,
	0xcc, 0x14, 0x09, 0x46, 0x05, 0x26, 0x0d, 0x3e, 0x23, 0x51, 0x3d, 0xb8, 0x4a, 0xbd, 0x00, 0x90,
	0xd6, 0xe4, 0xfc, 0x1c, 0xcf, 0x94, 0x20, 0x90, 0x0a, 0x21, 0x11, 0x2e, 0xd6, 0x80, 0x1c, 0x9f,
	0xd4, 0x3c, 0x09, 0x26, 0x05, 0x26, 0x0d, 0xde, 0x20, 0x08, 0x47, 0x48, 0x82, 0x8b, 0x3d, 0x20,
	0xb1, 0x32, 0x27, 0x3f, 0x31, 0x45, 0x82, 0x59, 0x81, 0x51, 0x83, 0x27, 0x08, 0xc6, 0x55, 0x3a,
	0xcf, 0xc8, 0xc5, 0x0f, 0xb1, 0xca, 0x23, 0x31, 0x2f, 0xa5, 0x38, 0x23, 0x31, 0x3b, 0x55, 0x48,
	0x8c, 0x8b, 0xcd, 0x2f, 0x3f, 0x25, 0xd5, 0x13, 0x62, 0x1f, 0x4f, 0x10, 0x94, 0x27, 0x24, 0xc5,
	0xc5, 0x01, 0xb6, 0xce, 0xaf, 0x34, 0x17, 0x6a, 0x3c, 0x9c, 0x2f, 0xe4, 0xc8, 0xc5, 0x09, 0x73,
	0x4a, 0xb1, 0x04, 0xb3, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0x32, 0x92, 0x33, 0xd1, 0xac, 0x80, 0x3b,
	0x3b, 0x08, 0xa1, 0x4b, 0xca, 0x15, 0x6a, 0x7c, 0x72, 0x7e, 0x0e, 0xf1, 0xfe, 0x15, 0xe0, 0x62,
	0x0e, 0x4b, 0x2d, 0x02, 0x3b, 0x87, 0x27, 0x08, 0xc4, 0xd4, 0x32, 0xe3, 0xe2, 0x42, 0x28, 0x12,
	0x12, 0xe6, 0xe2, 0x0f, 0x08, 0xf2, 0x0f, 0xf1, 0x8f, 0xf7, 0x70, 0xf4, 0x73, 0x09, 0xf6, 0x70,
	0xf4, 0x76, 0x15, 0x60, 0x10, 0x12, 0xe6, 0xe2, 0x83, 0x08, 0xba, 0x46, 0x84, 0xb8, 0x06, 0xf9,
	0x39, 0xfa, 0x08, 0xfc, 0x67, 0x74, 0x12, 0x38, 0xf1, 0x48, 0x8e, 0xf1, 0xc2, 0x23, 0x39, 0xc6,
	0x07, 0x8f, 0xe4, 0x18, 0x67, 0x3c, 0x96, 0x63, 0x00, 0x04, 0x00, 0x00, 0xff, 0xff, 0xa6, 0xda,
	0xfa, 0xc5, 0x9f, 0x01, 0x00, 0x00,
}
